version: '2'

services:
    projector:
        extends:
            file: docker/templates.yml
            service: php-cli
        command: php src/Common/projector.php

    projector_purchase:
        extends:
            file: docker/templates.yml
            service: php-cli
        command: php src/Purchase/projector.php

    projector_sales:
        extends:
            file: docker/templates.yml
            service: php-cli
        command: php src/Sales/projector.php

    process_manager:
        extends:
            file: docker/templates.yml
            service: php-cli
        command: php src/Common/process_manager.php
